### ISSUE TITLE
Where is file - dart.js?

### ISSUE THREAD

**Issue by vovs03** [davecom/Dart-for-Absolute-Beginners#1]
David, Hi!
Thank you for Book! 

**I really don't finded some Code in this repository.**
Look [Here](https://github.com/davecom/Dart-for-Absolute-Beginners/search?utf8=%E2%9C%93&q=dart.js&type=) You are included 10 times this path in 10 examples .html-files.
 But I cann't find `packages/browser/dart.js`

How this Code can Run?

**Comment by davecom** [comment]
Hi Vladimir,

Unfortunately the book was built around Dart Editor and all of the source code in this repository was structured to run in the Dart Editor environment. Dart Editor was the main IDE for Dart, distributed with the language at the time the book was written (2013-2014). Google chose to discontinue Dart Editor in 2015 somewhat deprecating the book and this repository. you should be able to still get the source code to run in a modern Dart environment, but it will require some modifications on your part.

I'm sorry for the inconvenience - it's a problem that comes with writing a book about a technology that is still a moving target. I wish they had not discontinued Dart Editor.

David
